name: test

on: 
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - development
      - main

jobs:
  check: CFMMMath
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run tests
        run: forge test -f${{ secrets.MAINNET_ENDPOINT }} 

      - name: Run snapshot
        run: forge snapshot -f${{ secrets.MAINNET_ENDPOINT }} 
